local lazy_options = {
  change_detection = {
    notify = false,
  },
  ui = {
    border = 'none',
    pills = true,
    icons = {
      cmd = '⌘ ',
      config = '☼',
      event = '▣',
      ft = '◆ ',
      init = '☇ ',
      import = '↘',
      keys = '₸ ',
      lazy = 'ℓ  ',
      loaded = '●',
      not_loaded = '○',
      plugin = '⏻',
      runtime = '◌',
      require = '☛',
      source = '☑',
      start = '▶',
      task = '✔ ',
      list = {
        '●',
        '-',
        '↳',
        '-',
        '↳',
        '-',
        '↳',
        '-',
        '↳',
        '-',
        '↳',
        '-',
        '↳',
        '-',
        '↳',
      },
    },
  },
}

return lazy_options
